### ISSUE TITLE
Task list for Editor (August 2016)

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#128]
- [ ] Replace synchronized LevelData store with the ArrayID-key based hash tables of scene items. That must improve performance and avoid having a duplicated data sets. And use LevelData store for a File I/O purposes only.
- [x] Add "Select all found elements" into the search toolbox
- [x] Improve detector of unused custom data to provide clean-up of unused data.
- [x] New custom stuff indexing system to have more convenient usage of customized stuff.
  It's a big work, but in result we will have much more convenient system to manage a custom stuff
- [ ] Add re-configurable hot-keys
- [ ] Speed-up render of editing scene with forcing of RTree usage with escaping usage of QGraphicsScene's update() function!
- [x] Implement ordering of elements by ID in the Item toolboxes
- [x] Add per lvl_block/lvl_bgo/lvl_npc/wld_tiles/etc. common grid value
- [x] Use lvl_characters.ini instead of main.ini to capture characters information
- [x] Make spoilers / scroll-area in the warps box to support view on smaller screens
- [ ] Add the Metric Tools - a non-game shapes which are can be used to meter distances, lengths, area sizes, and just use to know which area will be visible in game (which usually much smaller than editor view port).
- [x] "Open Episode folder in explorer" and "Open Custom folder in explorer" actions
- [x] Add function to refresh warp's entry XY coordninates inside combobox
- [x] Add "Replace all Item-ID in a current section" feature
- [x] Provide ability to define NPC's "friendly" flag from message editing dialog
- [x] Add multi-selection into ItemSelection dialog which needed for some cases
- [x] Finish incompleted work with garbage NPC clean function which provides removing of a junk NPCs
  spawned by SMBX Editor bug (such a vines and ladders): function anready finds junk NPC's
  but it doesn't removes them. Need to find and delete listed NPCs from scene and store the remove history entry.
- [x] Add R-Tree from engine into editor to increase performance of collision detection.
- [ ] "Smart placing" drawing feature which provides a transforming of nearest blocks by special rules to speed-up editing process. Provide an editor dialog to allow making custom smart placing schemes and rules.
- [ ] Flip/Rotating rules editor dialog (to allow user-friendly editing of auto-transforming rules when element was been flipped or rotated)

**Comment by Alucard648** [comment]
You forgot "smart blocks"/"auto paint" feature similar to one from SMBX-38A`s editor. Laying out ground edges tile-by-tile is most tedious work in editor.

**Comment by Wohlstand** [comment]
Added :wink:

**Comment by Alucard648** [comment]
Also:
1. Patterned fill/paint tool for faster drawing of patterned block structures, like SMB1 castle brick masonry. Of course, you could do that with copy/paste, but imaging filling large irregular holes with complex  block paterns. It`s very tedious.
2. Randomized fill/paint tool for random cracks and stones in ground. It`s very tedious to fill gaps with random blocks and stuff, like with Labyrinth Zone stone slabs. Imagine having to do that on constant basis  when working on long dungeon level with 40+ large sections.

**Comment by Wohlstand** [comment]
For the Re-Configurable hot keys the related article was found:
https://stackoverflow.com/questions/13435262/qt-user-customizable-hotkeys

**Comment by Wohlstand** [comment]
Closing this because of outdated.
Incomplete items recreating as separate tasks:
* #367
* #368 
* #369
* #370
