### ISSUE TITLE
Task list for Engine (August 2016)

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#129]
- [x] Replace QDialog-based config pack selection box with the own-drawn scene in the SDL Window
- [ ] Make global "loaderCallback" function pointer to allow processing of level/world loader screen from side without making of separated threads (which is not supported with single OpenGL context while texture loadings are in process)
- [x] Add ability to switch playable character from the world map's pause menu
- [ ] Exclamation sign sprite over talkable NPC's
- [ ] Fix support of huge textures (bigger than available by current OpenGL driver)
- [x] Fix a bug causes missing of custom lua-scripts declared in the custom npc.txt file
- [x] Replace all pixel per seconds NPC mover speeds with 1/64 second values
- [x] Raster fonts support
- [x] Textures support for world map items
- [x] Playable character and it's state switching support
- [x] Add loading of NPC configs: copy stuff from editor and replace QImage/QPixmap with a GL Textures.
- [x] Question box
- [x] Text input box to have able type a texts (Cheats, Messages, Save game filename, etc.)
- [x] Split sense of "scenery" argument to "scenery" and "shared-animation"
# Lua API's
- [ ] Better Memory Management, either transfere ownership to C++ or use smart pointers.
- [x] setFramePos() NPC Animator function to provide ability jump to any frame position in sequence
- [x] effect-def based effect spawn function to allow easier and flexible way of effect spawning
- [x] Detectors API for NPCs
- [x] Player-LUA events and allow external lua files like npc's are has.

``` Lua
-- Player's events function:
   onInit(...)
   onLoop(timeOfTick)
   onContact(physObject)
   onTake(physObject)
   onHarm(harmEvent)
   onKill(killEvent)
   onControl(key)
```
# Level physics
- [x] Smooth moving camera when going through door or pipe warp inside same section
- [x] Layer motion engine
  - [x] Use own R-Trees per every layer, register on main R-tree layer itself instead of it's members
- [x] R-Tree based physical world inside LevelScene with simple physics. PGE_PhysObj will a physical body
- [ ] Wall adheasing NPCs support 
- [ ] Fix staying of NPC's on a top of other flying NPC's
- [x] **Implement a new physical engine from [this repo](https://github.com/WohlSoft/MiniPhysics-By-38A)**

- [x] <s>Walkhable slopes</s>
- [x] <s>Kill on crush</s>
- [ ] <s>Complex effects scripts interpreter + bind of the effect-def into luna</s>
- [x] <s>Support of speed-adding of items which makes stack</s>

**Comment by Wohlstand** [comment]
After coming stable PGE Project toolchain release, I probably majorely rework entire platform of PGE Engine. I would to close this list and write new one.
