### ISSUE TITLE
Actualize config pack documentation at PGE Wiki [2020]

### ISSUE THREAD

**Issue by Wohlstand** [WohlSoft/PGE-Project#359]
Since a time, config pack got several updates of INI fields support. It's better to compare INI parsers and add missing fields updates.

**Comment by Wohlstand** [comment]
# TODO: 
## Synchronize and polish
- [x] Config pack [main page](https://wohlsoft.ru/pgewiki/Game_Configuration_Pack_References)
- [x] [main.ini](https://wohlsoft.ru/pgewiki/Main.ini_(Config_pack)) pages has been updated. 
- [ ] [NPC](https://wohlsoft.ru/pgewiki/NPC_Entry_INI_config_(Config_pack))
- [ ] [Blocks](https://wohlsoft.ru/pgewiki/Block_Entry_INI_config_(Config_pack))

## Verify
- [ ] [music.ini](https://wohlsoft.ru/pgewiki/Music.ini_(Config_pack))
- [ ] [sounds.ini](https://wohlsoft.ru/pgewiki/Sounds.ini_(Config_pack))
- [ ] [sound_riles.ini](https://wohlsoft.ru/pgewiki/Sound_roles.ini_(Config_pack))
- [ ] [*.font.ini](https://wohlsoft.ru/pgewiki/.font.ini_(Config_pack))
- [ ] [Editor themes](https://wohlsoft.ru/pgewiki/Theme_pack_for_editor)

## Split
- [ ] [BGO](https://wohlsoft.ru/pgewiki/Lvl_bgo.ini_(Config_pack))
- [ ] [Backgounds](https://wohlsoft.ru/pgewiki/Lvl_bkgrd.ini_(Config_pack))
- [ ] [Terrain](https://wohlsoft.ru/pgewiki/Wld_tiles.ini_(Config_pack))
- [ ] [Scenery](https://wohlsoft.ru/pgewiki/Wld_scenery.ini_(Config_pack))
- [ ] [Path](https://wohlsoft.ru/pgewiki/Wld_paths.ini_(Config_pack))
- [ ] [Levels](https://wohlsoft.ru/pgewiki/Wld_levels.ini_(Config_pack))
- [ ] [effects](https://wohlsoft.ru/pgewiki/Lvl_effects.ini_(Config_pack))

## Write:
- [ ] `configure.js` description and explanation
- [ ] lvl_characters.ini
- [ ] [engine.ini](https://wohlsoft.ru/pgewiki/Engine.ini_(Config_pack))
- [ ] [player calibration](https://wohlsoft.ru/pgewiki/Playable_character_calibration_(Config_pack))

**Comment by Wohlstand** [comment]
@nexia29, here is a list of pages for the proofreading. Please put a check once you had to complete the proofreading of a page:

- [ ] https://wohlsoft.ru/pgewiki/Game_Configuration_Pack_References
- [ ] https://wohlsoft.ru/pgewiki/Main.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Sounds.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Music.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Sound_roles.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Rotation_table.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Extra_Settings_JSON_Layout
- [ ] https://wohlsoft.ru/pgewiki/.font.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Lvl_npc.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/NPC_Entry_INI_config_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Lvl_blocks.ini_(Config_pack)
- [ ] https://wohlsoft.ru/pgewiki/Block_Entry_INI_config_(Config_pack)
- comming soon...

**Comment by Wohlstand** [comment]
Okay, the whole main work on the config pack has been completed!
The only last thing left - proofreading.

**Comment by Wohlstand** [comment]
I think the proofreading can be done separately, out of this task.
